name: Update AUR packages

on:
  # Manual trigger
  workflow_dispatch:

  # Cron trigger on the 1st day of every month at 00:00 UTC
  schedule:
    - cron: '0 0 1 * *'

jobs:  
  update-keyboard-app-aur:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install requests

      - name: Update AUR package
        env:
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
        run: |
          python main.py -p keyboard-app        
